USE [UpSkill_EscolaDelite]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
      AND TABLE_NAME = 'TiposRelacao'
)
BEGIN
CREATE TABLE [dbo].[TiposRelacao](
	[RelacaoID] [smallint] IDENTITY(1,1) NOT NULL,
	[RelacaoNome] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TipoRelacao] PRIMARY KEY CLUSTERED 
(
	[RelacaoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO

