USE [UpSkill_EscolaDelite]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo'
      AND TABLE_NAME = 'AlunosdaTurma'
)
BEGIN
CREATE TABLE [dbo].[AlunosdaTurma](
	[TurmaID] [bigint] NOT NULL,
	[AlunoID] [bigint] NOT NULL,
	[NotaFinal] [smallint] NULL,
	[DataAvaliacao] [datetime] NULL,
 CONSTRAINT [PK_AlunosdaTurma] PRIMARY KEY CLUSTERED 
(
	[TurmaID] ASC,
	[AlunoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO


