GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE Criar_Tabela_Turmas 
	
AS
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_SCHEMA = 'dbo'
		  AND TABLE_NAME = 'Turmas'
	)
	BEGIN
	CREATE TABLE [dbo].[Turmas](
		[TurmaID] [bigint] IDENTITY(1,1) NOT NULL,
		[AnoLetivoID] [bigint] NOT NULL,
		[CursoID] [bigint] NOT NULL,
		[AnoDoCurso] [smallint] NOT NULL,
	 CONSTRAINT [PK_Turmas] PRIMARY KEY CLUSTERED 
	(
		[TurmaID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]
	END
END
GO



