USE [Upskill_EscolaDelite]
GO

/****** Object:  Table [dbo].[TiposdeRelacao]    Script Date: 30/01/2026 15:00:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TiposdeRelacao](
	[RelacaoID] [smallint] IDENTITY(1,1) NOT NULL,
	[RelacaoNome] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TipoRelacao] PRIMARY KEY CLUSTERED 
(
	[RelacaoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

